---
version: 2.1

orbs:
  toolkit: jerus-org/circleci-toolkit@0.16.0

parameters:
  min-rust-version:
    type: string
    default: "1.74"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg

executors:
  rust_env:
    docker:
      - image: jerusdp/ci-rust:<<pipeline.parameters.min-rust-version>>

jobs:
  show_success:
    executor: rust_env
    steps:
      - run: |
          echo "Completed most successfully!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  validation:
    jobs:
      - toolkit/required_builds:
          name: required-builds
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/optional_builds:
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/test_doc_build:
          name: docs
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/common_tests:
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/idiomatic_rust:
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/update_changelog:
          requires:
            - toolkit/common_tests
            - required-builds
            - docs
            - toolkit/idiomatic_rust
          context:
            - release
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
          install_from_github: true
      - show_success:
          requires:
            - toolkit/update_changelog
